In [ ]:
!pip install nashpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nashpy as nash
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#数値=懲役年数
list = [
    ["2 or 2","10 or 0"],["10 or 0","5 or 5"]
    ]

In [ ]:
#黙秘と自白の選択肢が与えられる。
ind = ['Aの黙秘','Aの自白']
col = ['Bの黙秘','Bの自白']

df = pd.DataFrame(list,index=ind,columns=col)
df

Bの黙秘     Bの自白
Aの黙秘   2 or 2  10 or 0
Aの自白  10 or 0   5 or 5

In [ ]:
A = np.array([[2,0],[10,5]]) # 囚人Aの選択肢
B = np.array([[2,10],[0,5]]) # 囚人Bの選択肢
prisoners_dilemma = nash.Game(A,B)
prisoners_dilemma


Bi matrix game with payoff matrices:

Row player:
[[ 2  0]
 [10  5]]

Column player:
[[ 2 10]
 [ 0  5]]

In [ ]:
#ナッシュ均衡を求める
equilibria = prisoners_dilemma.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))
